services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile/Dockerfile_Ubuntu_Git
    image: ubuntu:git
    container_name: TestGit_01
    ports:
      - "7000:22"
    volumes:
      - "${HOST_GIT_PATH}:${MOUNT_PATH}"
      - "${HOST_SSH_PATH}:/data/host_ssh"
    environment:
      - http_proxy=http://${VPN_IP}:${VPN_PORT}
      - https_proxy=https://${VPN_IP}:${VPN_PORT}
      - all_proxy=http://${VPN_IP}:${VPN_PORT}
      - HOST_IP=${HOST_IP}
      - VPN_PORT=${VPN_PORT}
    command: >
      bash -c "
      ~/config.sh
      "
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 114.114.114.114
    stdin_open: true
    tty: true
    restart: unless-stopped