services:
  ubuntu:
    image: ubuntu:latest
    container_name: TestGit_01
    ports:
      - "7000:22"
    volumes:
      - "${HOST_GIT_PATH}:${MOUNT_PATH}"
      - ./Template_Ubuntu:/data/Template_Ubuntu
      - "${HOST_SSH_PATH}:/data/host_ssh"
    environment:
      - http_proxy=http://${VPN_IP}:${VPN_PORT}
      - https_proxy=https://${VPN_IP}:${VPN_PORT}
      - all_proxy=http://${VPN_IP}:${VPN_PORT}
      - HOST_IP=${HOST_IP}
      - VPN_PORT=${VPN_PORT}
      - DEBIAN_FRONTEND=noninteractive
    command: >
      bash -c "
      chmod +x /data/Template_Ubuntu/root/config.sh &&
      /data/Template_Ubuntu/root/config.sh
      "
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    dns:
      - 8.8.8.8
      - 114.114.114.114
    stdin_open: true
    tty: true
    restart: unless-stopped